{"uid":"fc65b51015433863","name":"Тест на получение сообщения. Негативный. Неверный messageId","fullName":"api_test.tests.test_get_message#test_get_message_negative_not_found","historyId":"bf367d947fc332f6ed88b07e072c3de6","time":{"start":1732980694899,"stop":1732980694991,"duration":92},"status":"failed","statusMessage":"Failed: Error: 401","statusTrace":"get_message_endpoint = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7f9f1a9e95a0>\nheaders = {'Authorization': 'Bot MTI4NjYwOTgxOTEzNzk5ODg4Mw.Gj2Mlk.YsVgU6PYv7xVW5bl7RYt9DLg2QeCU4OXToIiSw', 'Content-Type': 'application/json'}\n\n    @allure.title(\"Тест на получение сообщения. Негативный. Неверный messageId\")\n    def test_get_message_negative_not_found(get_message_endpoint, headers):\n        with allure.step(\"Отправка запроса\"):\n            get_message_endpoint.get_message_request(headers, 123)\n        with allure.step(\"Проверка статус кода\"):\n>           get_message_endpoint.check_status_code(404)\n\napi_test/tests/test_get_message.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7f9f1a9e95a0>\ncode = 404\n\n    def check_status_code(self, code):\n        if self.response.status_code == code:\n            pass\n        else:\n>           pytest.fail(f'Error: {self.response.status_code}')\nE           Failed: Error: 401\n\napi_test/endpoints/base_endpoint.py:35: Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"headers","time":{"start":1732980694899,"stop":1732980694899,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"get_message_endpoint","time":{"start":1732980694899,"stop":1732980694899,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"Failed: Error: 401","statusTrace":"get_message_endpoint = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7f9f1a9e95a0>\nheaders = {'Authorization': 'Bot MTI4NjYwOTgxOTEzNzk5ODg4Mw.Gj2Mlk.YsVgU6PYv7xVW5bl7RYt9DLg2QeCU4OXToIiSw', 'Content-Type': 'application/json'}\n\n    @allure.title(\"Тест на получение сообщения. Негативный. Неверный messageId\")\n    def test_get_message_negative_not_found(get_message_endpoint, headers):\n        with allure.step(\"Отправка запроса\"):\n            get_message_endpoint.get_message_request(headers, 123)\n        with allure.step(\"Проверка статус кода\"):\n>           get_message_endpoint.check_status_code(404)\n\napi_test/tests/test_get_message.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.endpoints.get_message_endpoint.GetMessageEndpoint object at 0x7f9f1a9e95a0>\ncode = 404\n\n    def check_status_code(self, code):\n        if self.response.status_code == code:\n            pass\n        else:\n>           pytest.fail(f'Error: {self.response.status_code}')\nE           Failed: Error: 401\n\napi_test/endpoints/base_endpoint.py:35: Failed","steps":[{"name":"Отправка запроса","time":{"start":1732980694899,"stop":1732980694991,"duration":92},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"Проверка статус кода","time":{"start":1732980694991,"stop":1732980694991,"duration":0},"status":"failed","statusMessage":"Failed: Error: 401\n","statusTrace":"  File \"/home/runner/work/diplom/diplom/api_test/tests/test_get_message.py\", line 9, in test_get_message_negative_not_found\n    get_message_endpoint.check_status_code(404)\n  File \"/home/runner/work/diplom/diplom/api_test/endpoints/base_endpoint.py\", line 35, in check_status_code\n    pytest.fail(f'Error: {self.response.status_code}')\n  File \"/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":2,"attachmentsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"api_test.tests"},{"name":"suite","value":"test_get_message"},{"name":"host","value":"fv-az1251-280"},{"name":"thread","value":"2086-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api_test.tests.test_get_message"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"fc65b51015433863.json","parameterValues":[]}